type            = "cron"
schemaVersion   = 1
name = "Validator Slice 1"
schedule        = "CRON_TZ=UTC @every 0m10s"
observationSource   = """

    hash_encode_call  [type="ethabiencode"
                abi="getHash()"
                data=""]

    hash_call          [type="ethcall"
                contract="0x5DFA168a9e089b3FEc11f5ADCbE54D922D294D44"
                data="$(hash_encode_call)"]

    hash_decode_result [type="ethabidecode"
                abi="string hashIpfs"
                data="$(hash_call)"]

    path_encode_call  [type="ethabiencode"
                abi="getPath()"
                data=""]

    path_call [type="ethcall"
                contract="0x5DFA168a9e089b3FEc11f5ADCbE54D922D294D44"
                data="$(path_encode_call)"]

    path_decode_result [type="ethabidecode"
                abi="string path"
                data="$(path_call)"]


    my_bridge_task [type="bridge"
                name="validate-bridge"
                requestData="{ \\"data\\": { \\"hashIpfs\\": $(hash_decode_result.hashIpfs), \\"path\\": $(path_decode_result.path) }}"
                ]

    hash_encode_call -> hash_call -> hash_decode_result -> my_bridge_task
    path_encode_call -> path_call -> path_decode_result  -> my_bridge_task
"""