version: "3"

services:
  ipfs:
    container_name: ipfs

    image: ipfs/go-ipfs:v0.8.0

    ports:
    - 4001:4001
    - 4001:4001/udp
    - 127.0.0.1:8080:8080
    - 127.0.0.1:5001:5001

    volumes:
    - ./ifps/export:/export
    - ./ipfs/data:/data/ipfs